---
title: "Implementation and Evaluation of Estimator for S2S sMRT Treatment Excursion Effects"
author: |
    |
date: '`r format(Sys.Date(), "%B %d, %Y")`'
geometry: margin=1in
output: 
  pdf_document:
    number_sections: TRUE
---

# Scenario 1

## Data Structure

We index the decision points over the course of the study by $t = 1,2,3,...$. When there is no missing data, the data ordering is

$$
(Y_1, I_1, X_1, p_1(H_1), A_1), (Y_2, I_2, X_2, p_2(H_2), A_2), (Y_3, I_3, X_3, p_3(H_3), A_3), ...
$$
where

$$
Y_t =
\begin{cases}
1 \hspace{0.5cm}\text{if}\hspace{0.3cm} \text{stressed at t} \\
2 \hspace{0.5cm}\text{if}\hspace{0.3cm} \text{physically active at t} \\
3 \hspace{0.5cm}\text{if}\hspace{0.3cm} \text{not stressed at t} \\
\end{cases}
$$


$$
I_t =
\begin{cases}
0 \hspace{0.5cm}\text{if}\hspace{0.3cm} \text{randomization did not occur} \\
1 \hspace{0.5cm}\text{if}\hspace{0.3cm} \text{randomization occurred}
\end{cases}
$$

$$
X_t =
\begin{cases}
1 \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_t=1 \\
0 \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_t=3 \\
\text{n/a} \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_t=2
\end{cases}
$$

$$
A_t \big| H_t \sim Bern(p(H_t))
$$

In other words, in Scenario 1, the dataset that a data analyst will have on hand will contain the following data

$$
(Y_1, I_1, X_1, p_1(H_1), A_1), (Y_2, I_2, X_2, p_2(H_2), A_2), (Y_3, I_3, X_3, p_3(H_3), A_3), ...
$$


## Causal Effect of Interest


* $\frac{Pr\left\{Y_{t+1}\left(\bar{A}_{t-1}, 1\right) = 1 | I_t = 1, X_t = 1\right\}}{Pr\left\{Y_{t+1}\left(\bar{A}_{t-1}, 0\right) = 1 | I_t = 1, X_t = 1\right\}}$

* $\frac{Pr\left\{Y_{t+1}\left(\bar{A}_{t-1}, 1\right) = 1 | I_t = 1, X_t = 0\right\}}{Pr\left\{Y_{t+1}\left(\bar{A}_{t-1}, 0\right) = 1 | I_t = 1, X_t = 0\right\}}$

* $\frac{Pr\left\{Y_{t+1}\left(\bar{A}_{t-1}, 1\right) = 3 | I_t = 1, X_t = 1\right\}}{Pr\left\{Y_{t+1}\left(\bar{A}_{t-1}, 0\right) = 3 | I_t = 1, X_t = 1\right\}}$

* $\frac{Pr\left\{Y_{t+1}\left(\bar{A}_{t-1}, 1\right) = 3 | I_t = 1, X_t = 0\right\}}{Pr\left\{Y_{t+1}\left(\bar{A}_{t-1}, 0\right) = 3 | I_t = 1, X_t = 0\right\}}$


## Data Generating Model

For each individual, we have the following data generating process:

* **Determine classification at each decision point $t$:** $Y_1, Y_2, ..., Y_T$ are independent and identically distributed

$$
Y_t \sim Multinom \left(q_1, q_2, q_3\right)
$$

where $q_1 + q_3 + q_3 = 1$ and $q_1, q_2, q_3$ are the probabilities corresponding to the stressed (i.e., $Y_t=1$), physically active (i.e., $Y_t=2$), and not stressed (i.e., $Y_t=3$) categories, respectively.

* **Determine whether randomization will occur at each decision point $t$:**

$$
I_t =
\begin{cases}
0 \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_t=2 \\
1 \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_t=1  \text{ or } Y_t=3 
\end{cases}
$$

In other words, randomization will not occur during decision points for which the individual is classified as physically active. Additionally, in contrast with study protocol, we make the simplification that even if an intervention was offered at the current decision point (i.e., $A_t = 1$), that we would still allow randomization at the next decision point (i.e., at $t+1$) as long as the individual was not classified as physically active at the next decision point (i.e., as long as $Y_{t+1} \neq 2$).

* **Construct stratification variable at each decision point $t$:**

$$
X_t =
\begin{cases}
1 \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_t=1 \\
0 \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_t=3 \\
\text{n/a} \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_t=2
\end{cases}
$$

* **Calculate the randomization probabilities at the current decision point $t$:** We make the simplification that randomization probabilities do not depend on the individual's entire history up to the current decision point $t$ (i.e., $H_t$), but rather, only on a portion of the individual's entire history. Specifically, we set the randomization probabilities to be solely dependent on $Y_{t-1}$ and $X_t$. Hence, notation simplifies to $p_t(H_t) = p(Y_{t-1}, X_t)$. For all $t$, the randomization probabilities are

$$
p(Y_{t-1}, X_t) := Pr \left\{ A_t = 1 | Y_{t-1}, X_t \right\} =
\begin{cases}
r_{1,1} \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_{t-1}=1 \text{ and } X_t=1 \\
r_{1,0} \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_{t-1}=1  \text{ and } X_t=0 \\
r_{2,1} \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_{t-1}=2  \text{ and } X_t=1 \\
r_{2,0} \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_{t-1}=2  \text{ and } X_t=0 \\
r_{3,1} \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_{t-1}=3  \text{ and } X_t=1 \\
r_{3,0} \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_{t-1}=3  \text{ and } X_t=0 \\
0 \hspace{0.9cm}\text{otherwise, i.e., when physically active at current decision point } t\\
\end{cases}
$$

In this way, the randomization probabilities within each strata can vary from participant to participant.

* **Determine randomization assignment at the current decision point $t$ only if $I_t=1$:** 

$$
A_t \big| Y_{Y_t-1}, X_t \sim Bern(p(Y_{t-1}, X_t))
$$

For example, if $Y_{t-1}=3  \text{ and } X_t=1$ (i.e., classified as not stressed at $t-1$ but classified as stressed at $t$)  then $A_t \big| Y_{Y_t-1}=3, X_t=1 \sim Bern(r_{3,1})$.

## Inputs to Data Generating Model

Values for the following parameters will be specified prior to employing the data generating model:

* $T$, total number of decision points

* $N$, total number of participants

* $q_1, q_2, q_3$

* $r_{1,1}, r_{2,1}, r_{3,1}, r_{1,0}, r_{2,0}, r_{3,0}$


## Implied Weights

The product term in the weight is not necessary, i.e., the weight is

$$
\widehat{W}_t(x) =
\begin{cases}
\frac{\widehat{p}(x)}{Pr \left\{ A_t = 1 | Y_{t-1}, X_t \right\}} \hspace{0.5cm}\text{if}\hspace{0.3cm} A_t=1\\
\frac{1 - \widehat{p}(x)}{1 - Pr \left\{ A_t = 1 | Y_{t-1}, X_t \right\}} \hspace{0.5cm}\text{if}\hspace{0.3cm} A_t=0\
\end{cases}
$$

where 

$$
\widehat{p}(x) = \frac{\widehat{E}\left\{\sum_{t=1}^T I_t \cdot 1(X_t=x) \cdot Pr \left\{ A_t = 1 | Y_{t-1}, X_t \right\} \right\}}{\widehat{E}\left\{\sum_{t=1}^T I_t \cdot 1(X_t=x) \right\}}
$$ 


Due to the choice of data generating model in Scenario 1, it is tractable to write the probability limit of $\widehat{p}(x)$, i.e., $p(x)$, in terms of the data generating parameters. 

Specifically, the denominator of $p(x)$ can be obtained from the following quantities


$$
E\left\{\sum_{t=1}^T I_t \cdot 1(X_t=1) \right\} = T \cdot q_1
$$

$$
E\left\{\sum_{t=1}^T I_t \cdot 1(X_t=0) \right\} = T \cdot q_3
$$

and the numerator of $p(x)$ can be obtained from the following quantities

$$
E\left\{\sum_{t=1}^T I_t \cdot 1(X_t=1) \cdot Pr \left\{ A_t = 1 | Y_{t-1}, X_t \right\} \right\} = T \cdot \left( r_{1,1} \cdot q_1 + r_{2,1}  \cdot q_2 + r_{3,1}  \cdot q_3 \right) \cdot q_1
$$

$$
E\left\{\sum_{t=1}^T I_t \cdot 1(X_t=0) \cdot Pr \left\{ A_t = 1 | Y_{t-1}, X_t \right\} \right\} = T \cdot \left( r_{1,0}  \cdot q_1 + r_{2,0} \cdot q_2 + r_{3,0} \cdot q_3 \right) \cdot q_3
$$


# Scenario 2

Simulation will involve two stages. 

**Stage 1:** The data generating model will follow that of Scenario 1, but additionally, for each decision point, we will generate a missing data indicator $M_t$ and an observe data outcome $Y_t^*$. Hence, in the first stage, the data ordering is

$$
(Y_1, I_1, X_1, p_1(H_1), A_1, M_1, Y_1^*), (Y_2, I_2, X_2, p_2(H_2), A_2, M_2, Y_2^*), (Y_3, I_3, X_3, p_3(H_3), A_3, M_3, Y_3^*), ...
$$

where

$$
M_t =
\begin{cases}
1 \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_t \hspace{0.3cm} \text{will be observed by the data analyst}\\
0 \hspace{0.5cm}\text{if}\hspace{0.3cm} Y_t \hspace{0.3cm} \text{will be missing (unobserved by the data analyst)} \\
\end{cases}
$$


$$
M_t \sim Bern(p(H_t))
$$

$$
Y_t^* =
\begin{cases}
Y_t \hspace{0.5cm}\text{if}\hspace{0.3cm} M_t=1 \\
N/A \hspace{0.5cm}\text{if}\hspace{0.3cm} M_t=0 \\
\end{cases}
$$
**Stage 2:** In the second stage, we construct the dataset that will be observed by the data analyst. This dataset will contain the following variables only

$$
(I_1, X_1, p_1(H_1), A_1, M_1, Y_1^*), (I_2, X_2, p_2(H_2), A_2, M_2, Y_2^*), (I_3, X_3, p_3(H_3), A_3, M_3, Y_3^*), ...
$$

